//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.SvTareo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BE_PERSONAL_GESTOR", Namespace="http://schemas.datacontract.org/2004/07/BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class BE_PERSONAL_GESTOR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDO_MATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDO_PATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CENTRO_COSTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CENTRO_COSTO_ORIGENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_TRABAJADORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOCUMENTO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_ACTUALIZACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOTIVO_CESEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO_MATERNO {
            get {
                return this.APELLIDO_MATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDO_MATERNOField, value) != true)) {
                    this.APELLIDO_MATERNOField = value;
                    this.RaisePropertyChanged("APELLIDO_MATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO_PATERNO {
            get {
                return this.APELLIDO_PATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDO_PATERNOField, value) != true)) {
                    this.APELLIDO_PATERNOField = value;
                    this.RaisePropertyChanged("APELLIDO_PATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CENTRO_COSTO {
            get {
                return this.CENTRO_COSTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CENTRO_COSTOField, value) != true)) {
                    this.CENTRO_COSTOField = value;
                    this.RaisePropertyChanged("CENTRO_COSTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CENTRO_COSTO_ORIGEN {
            get {
                return this.CENTRO_COSTO_ORIGENField;
            }
            set {
                if ((this.CENTRO_COSTO_ORIGENField.Equals(value) != true)) {
                    this.CENTRO_COSTO_ORIGENField = value;
                    this.RaisePropertyChanged("CENTRO_COSTO_ORIGEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_TRABAJADOR {
            get {
                return this.CODIGO_TRABAJADORField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_TRABAJADORField, value) != true)) {
                    this.CODIGO_TRABAJADORField = value;
                    this.RaisePropertyChanged("CODIGO_TRABAJADOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOCUMENTO_IDENTIFICACION {
            get {
                return this.DOCUMENTO_IDENTIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DOCUMENTO_IDENTIFICACIONField, value) != true)) {
                    this.DOCUMENTO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("DOCUMENTO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_ACTUALIZACION {
            get {
                return this.FECHA_ACTUALIZACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_ACTUALIZACIONField, value) != true)) {
                    this.FECHA_ACTUALIZACIONField = value;
                    this.RaisePropertyChanged("FECHA_ACTUALIZACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_CREACION {
            get {
                return this.FECHA_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_CREACIONField, value) != true)) {
                    this.FECHA_CREACIONField = value;
                    this.RaisePropertyChanged("FECHA_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOTIVO_CESE {
            get {
                return this.MOTIVO_CESEField;
            }
            set {
                if ((object.ReferenceEquals(this.MOTIVO_CESEField, value) != true)) {
                    this.MOTIVO_CESEField = value;
                    this.RaisePropertyChanged("MOTIVO_CESE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRES {
            get {
                return this.NOMBRESField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESField, value) != true)) {
                    this.NOMBRESField = value;
                    this.RaisePropertyChanged("NOMBRES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvTareo.ITareo")]
    public interface ITareo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITareo/ProbarConexion", ReplyAction="http://tempuri.org/ITareo/ProbarConexionResponse")]
        WebApplication.SvTareo.ProbarConexionResponse ProbarConexion(WebApplication.SvTareo.ProbarConexionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITareo/ProbarConexion", ReplyAction="http://tempuri.org/ITareo/ProbarConexionResponse")]
        System.Threading.Tasks.Task<WebApplication.SvTareo.ProbarConexionResponse> ProbarConexionAsync(WebApplication.SvTareo.ProbarConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITareo/ListarPersonalGestor", ReplyAction="http://tempuri.org/ITareo/ListarPersonalGestorResponse")]
        WebApplication.SvTareo.ListarPersonalGestorResponse ListarPersonalGestor(WebApplication.SvTareo.ListarPersonalGestorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITareo/ListarPersonalGestor", ReplyAction="http://tempuri.org/ITareo/ListarPersonalGestorResponse")]
        System.Threading.Tasks.Task<WebApplication.SvTareo.ListarPersonalGestorResponse> ListarPersonalGestorAsync(WebApplication.SvTareo.ListarPersonalGestorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProbarConexion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProbarConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string as_error;
        
        public ProbarConexionRequest() {
        }
        
        public ProbarConexionRequest(string as_error) {
            this.as_error = as_error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProbarConexionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProbarConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProbarConexionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string as_error;
        
        public ProbarConexionResponse() {
        }
        
        public ProbarConexionResponse(bool ProbarConexionResult, string as_error) {
            this.ProbarConexionResult = ProbarConexionResult;
            this.as_error = as_error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPersonalGestor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPersonalGestorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IDE_EMPRESA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CENTRO_COSTO;
        
        public ListarPersonalGestorRequest() {
        }
        
        public ListarPersonalGestorRequest(int IDE_EMPRESA, string CENTRO_COSTO) {
            this.IDE_EMPRESA = IDE_EMPRESA;
            this.CENTRO_COSTO = CENTRO_COSTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPersonalGestorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPersonalGestorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.SvTareo.BE_PERSONAL_GESTOR[] ListarPersonalGestorResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msgerror;
        
        public ListarPersonalGestorResponse() {
        }
        
        public ListarPersonalGestorResponse(WebApplication.SvTareo.BE_PERSONAL_GESTOR[] ListarPersonalGestorResult, string msgerror) {
            this.ListarPersonalGestorResult = ListarPersonalGestorResult;
            this.msgerror = msgerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITareoChannel : WebApplication.SvTareo.ITareo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TareoClient : System.ServiceModel.ClientBase<WebApplication.SvTareo.ITareo>, WebApplication.SvTareo.ITareo {
        
        public TareoClient() {
        }
        
        public TareoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TareoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TareoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TareoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.SvTareo.ProbarConexionResponse WebApplication.SvTareo.ITareo.ProbarConexion(WebApplication.SvTareo.ProbarConexionRequest request) {
            return base.Channel.ProbarConexion(request);
        }
        
        public bool ProbarConexion(ref string as_error) {
            WebApplication.SvTareo.ProbarConexionRequest inValue = new WebApplication.SvTareo.ProbarConexionRequest();
            inValue.as_error = as_error;
            WebApplication.SvTareo.ProbarConexionResponse retVal = ((WebApplication.SvTareo.ITareo)(this)).ProbarConexion(inValue);
            as_error = retVal.as_error;
            return retVal.ProbarConexionResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication.SvTareo.ProbarConexionResponse> ProbarConexionAsync(WebApplication.SvTareo.ProbarConexionRequest request) {
            return base.Channel.ProbarConexionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.SvTareo.ListarPersonalGestorResponse WebApplication.SvTareo.ITareo.ListarPersonalGestor(WebApplication.SvTareo.ListarPersonalGestorRequest request) {
            return base.Channel.ListarPersonalGestor(request);
        }
        
        public WebApplication.SvTareo.BE_PERSONAL_GESTOR[] ListarPersonalGestor(int IDE_EMPRESA, string CENTRO_COSTO, out string msgerror) {
            WebApplication.SvTareo.ListarPersonalGestorRequest inValue = new WebApplication.SvTareo.ListarPersonalGestorRequest();
            inValue.IDE_EMPRESA = IDE_EMPRESA;
            inValue.CENTRO_COSTO = CENTRO_COSTO;
            WebApplication.SvTareo.ListarPersonalGestorResponse retVal = ((WebApplication.SvTareo.ITareo)(this)).ListarPersonalGestor(inValue);
            msgerror = retVal.msgerror;
            return retVal.ListarPersonalGestorResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication.SvTareo.ListarPersonalGestorResponse> ListarPersonalGestorAsync(WebApplication.SvTareo.ListarPersonalGestorRequest request) {
            return base.Channel.ListarPersonalGestorAsync(request);
        }
    }
}
